name: Pack Documentation

on: [push]

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set current date
        run: echo "CUR_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Documentation-${{ env.CUR_DATE }}
          path: ./docs/*