name: Pack&Release

on: [push, pull_request]

permissions:
  contents: write

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read pack.mcmeta
        id: read_pack
        run: |
          DESCRIPTION=$(jq -r '.pack.description' pack.mcmeta)
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: RailwayAesthetics-Future ${{ env.DESCRIPTION }}
          path: |
            assets/
            pack.mcmeta
            pack.png
            LICENSE
            readme.md
  release:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: RailwayAesthetics-Future ${{ needs.pack.outputs.DESCRIPTION }}
          path: download/
      - name: Release
        with:
          files: download/RailwayAesthetics-Future ${{ needs.pack.outputs.DESCRIPTION }}.zip
          body: 一些更新
          draft: false
          prerelease: false