name: Pack&Release

on: [push, pull_request]

permissions:
  contents: write

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read pack.mcmeta
        id: read_pack
        run: |
          DESCRIPTION=$(jq -r '.pack.description' pack.mcmeta)
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: RailwayAesthetics-Future ${{ env.DESCRIPTION }}
          path: |
            assets/
            pack.mcmeta
            pack.png
            LICENSE
            readme.md
  release:
    if: startsWith(github.event.head_commit.message, 'rel')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read pack.mcmeta
        id: read_pack
        run: |
          DESCRIPTION=$(git describe --tags --abbrev=0)
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
      - name: Create Zip
        run: zip -r "RailwayAesthetics-Future ${{ env.DESCRIPTION }}.zip" assets/ pack.mcmeta pack.png LICENSE readme.md
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: RailwayAesthetics-Future ${{ env.DESCRIPTION }}.zip
          body: 一些更新
          draft: false
          prerelease: false
          tag_name: ${{ env.DESCRIPTION }}