name: Pack&Release

on: [push, pull_request]

permissions:
  contents: write

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read pack.mcmeta
        id: read_pack
        run: |
          DESCRIPTION=$(jq -r '.pack.description' pack.mcmeta)
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: RailwayAesthetics-Future ${{ env.DESCRIPTION }}
          path: |
            assets/
            pack.mcmeta
            pack.png
            LICENSE
            readme.md
  release:
    if: startsWith(github.event.head_commit.message, 'rel')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read pack.mcmeta
        id: read_pack
        run: |
          DESCRIPTION=$(jq -r '.pack.description' pack.mcmeta)
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
      - name: Create Zip
        run: zip -r "RailwayAesthetics-Future ${{ env.DESCRIPTION }}.zip" assets/ pack.mcmeta pack.png LICENSE readme.md
      - name: Set current date
        run: echo "CUR_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Get commit SHA
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: RailwayAesthetics-Future ${{ env.DESCRIPTION }}.zip
          body: |
            更新日期: ${{ env.CUR_DATE }}
            当前工作流: [${{ env.SHA_SHORT }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            更新内容:

            相关链接:
            - [RailwayAesthetics-Future文档](https://aphrodite281.github.io/RailwayAesthetics-Future/#/)
            - [ANTE文档](https://aphrodite281.github.io/mtr-ante/#/)
            - [RailwayAesthetics-Future发行版](https://github.com/aphrodite281/RailwayAesthetics-Future/releases)
            - [ANTE发行版](https://github.com/aphrodite281/mtr-ante/releases)
          draft: false
          prerelease: false
          tag_name: ${{ env.DESCRIPTION }}