name: Pack and Release

on:
  push:
    tags:
      - 'rel*'

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read pack.mcmeta
        id: read_pack
        run: |
          DESCRIPTION=$(jq -r '.pack.description' pack.mcmeta)
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          zip -r RailwayAesthetics-Future-${{ env.DESCRIPTION }}.zip assets/ pack.mcmeta pack.png LICENSE readme.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.DESCRIPTION }}
          release_name: Release ${{ env.DESCRIPTION }}
          draft: false
          prerelease: false

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./RailwayAesthetics-Future-${{ env.DESCRIPTION }}.zip
          asset_name: RailwayAesthetics-Future-${{ env.DESCRIPTION }}.zip
          asset_content_type: application/zip