name: Pack and Release

on:
  push:
    tags:
      - 'rel*'

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read pack.mcmeta
        id: read_pack
        run: |
          DESCRIPTION=$(jq -r '.pack.description' pack.mcmeta)
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          zip -r RailwayAesthetics-Future-${{ env.DESCRIPTION }}.zip assets/ pack.mcmeta pack.png LICENSE readme.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: RailwayAesthetics-Future-${{ env.DESCRIPTION }}.zip
          name: RailwayAesthetics-Future ${{ env.DESCRIPTION }}
          body: 一些更新